# Generated by Django 5.2.3 on 2025-06-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_category_options_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product_sales",
            options={
                "ordering": ["-order_date"],
                "verbose_name_plural": "Products_Sales",
            },
        ),
    ]
